language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user:
    secure: gYo7u97wN5JyE1/pjkMzMhun6DnxZ1orE3gQ2Def1UPHS031/LdXGlsmPs6npLaBK5jfDMT4a+7qRyEvBZwh9izznzy/NDDD5+bwy9b+/sjIRdQvLy4YTq7obEcuRGdKeehAfkkYRCa0EEEgLwxQqJuhE07EvTTFvj3xws7Cvva9QorzNUA54mqRUIfzg4Kgms5JMDhmUyyBYq/AMTIG/+yNm/jcGxR4t+mGlmOepImQMn61udbe1ky+1c+5Fji/09N9PyUG3aSoMYyn2mquwDCs6KC/T/tvE0FeM+O2iqhZieviVLVkBJ1HG32IFdFXTSWZZ61RU1amihMSKapgEUYtTAqXszKJ6Gzcwgw3paHARVDt+6Ij9MLHp+O4g7mMnQ0T8pJe+R/Oi6gaeDLiqNEFaYPVOrvfCDzFzDYCUMjixnyZvOcjUdC5y3P8IRyhjRygBUNwF4XjMER9maQcwFtWy62Zy5uc9cyT2sUL7sHhqtfl0QD+UdseWGOF1Y3ITpNbUTDQv1HezOIQb44ifM8toQFX9zN41eG/jrhrCfmKCY6UbMR/Lm9F6tkQaxHuAOh+160E9ikEDE+pWrlWujkBT35pEdLOG1xiMNJNIURTVY+ySbcVKUlSd/qKj1Z2PbcsVnfDJ/cLkVTTSTlHt444i9Cc+Eai9yhp+owVRts=
  password:
    secure: PHYt1yJ5lF/Sdea/hV1A6DDzi6ebYcsDyy3FT7qU04MatAF+D3w/SN2IMd21lPcInOMJNDwucYEv66QThPcylGT33iImoqnE3Xae7XbN0DA9Gnd0qbMLApLfDlVwvYtHvjK8BcMDUK3BbHvE3p7U9BxsvAM91At6/ifWZJRbApskpuqkZiwDF1C4MO0m+DgcGvPySZzEPyJ4nfEvaytJ+Qp0r1Xb5tzAZWtiEeN3A2tjWy/V0dLmM6tllcuAiOs49Zn9MpuXOqSzgj4p2R6mzPGzt6CkhpCP0gM66KysD9XMrnTMcIra+qafB9ZU8BrtZr3B7icVIJD2lC1NbqMBwfgjtLp07AafRT73KVLsIg9q2YHjDDJVoNEDQ2n0gVyLjbemLIzpZxNKZ3xQYDenzpkS6KAvlkW1kIe5UL4tqpvzyNxC3uacjBSLOERhj+D2lAofyVgv5K5XJtjMrSBEqWBLdu/NhzTdQ1OLuaWpHz3qTopd4/hJ2z0ec6GOE5vJp3HgHjRhbPaKWlffj5ccjyDiBkLccERjrl7THpsyL9/1j/8MXfzBZDnVRH9XY5JfYtuWXkWDPr6Yrv1oz3rAdAySI+Z10DjmXNhrc4Dk59IAUDAsbyyOpf4UuHidH4VhmeDhDsXRAFcZkDJ3sYATEc4MCmG7c7HRWsAM59DOyAU=
  on:
    tags: true
