name: Launch tests

on:
  pull_request:
    types: [synchronize]
  push:
    branches:
      - dev
      - master
    tags:
      - test*

jobs:
  test:
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip &&
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64
      - name: Install Dependencies
        run:
          python -m pip install --upgrade pip &&
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
